

import '../src/features/job_board/models/company_model.dart';
import '../src/features/job_board/models/job_model.dart';

class MockData {
  static List<JobModel> getRecommendedJobs() {
    return [
      JobModel(
        id: '1',
        title: 'UX/UI Designer',
        companyName: 'Gofive',
        companyLogo: 'https://via.placeholder.com/60',
        matchPercentage: 89,
        level: 'Senior',
        workType: 'Full time',
        location: 'Bangkok',
        salaryRange: '200,000 - 350,000',
        postedAt: DateTime.now().subtract(const Duration(minutes: 1)),
      ),
      JobModel(
        id: '2',
        title: 'Sales Manager',
        companyName: 'Gofive',
        companyLogo: 'https://via.placeholder.com/60',
        matchPercentage: 79,
        level: 'Senior',
        workType: 'Full time',
        location: 'Bangkok',
        salaryRange: '200,000 - 350,000',
        postedAt: DateTime.now().subtract(const Duration(minutes: 1)),
      ),
      JobModel(
        id: '3',
        title: 'Onboarding Specialist',
        companyName: 'Gofive',
        companyLogo: 'https://via.placeholder.com/60',
        matchPercentage: 78,
        level: 'Senior',
        workType: 'Full time',
        location: 'Bangkok',
        salaryRange: '200,000 - 350,000',
        postedAt: DateTime.now().subtract(const Duration(minutes: 1)),
      ),
      JobModel(
        id: '4',
        title: 'Onboarding Specialist',
        companyName: 'Gofive',
        companyLogo: 'https://via.placeholder.com/60',
        matchPercentage: 78,
        level: 'Senior',
        workType: 'Full time',
        location: 'Bangkok',
        salaryRange: '200,000 - 350,000',
        postedAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      JobModel(
        id: '5',
        title: 'Frontend Developer',
        companyName: 'TechCorp',
        companyLogo: 'https://via.placeholder.com/60',
        matchPercentage: 85,
        level: 'Mid-level',
        workType: 'Full time',
        location: 'Bangkok',
        salaryRange: '150,000 - 250,000',
        postedAt: DateTime.now().subtract(const Duration(hours: 3)),
      ),
      JobModel(
        id: '6',
        title: 'Data Scientist',
        companyName: 'DataTech',
        companyLogo: 'https://via.placeholder.com/60',
        matchPercentage: 92,
        level: 'Senior',
        workType: 'Full time',
        location: 'Bangkok',
        salaryRange: '300,000 - 450,000',
        postedAt: DateTime.now().subtract(const Duration(hours: 5)),
      ),
      JobModel(
        id: '7',
        title: 'Product Manager',
        companyName: 'Innovation Inc',
        companyLogo: 'https://via.placeholder.com/60',
        matchPercentage: 87,
        level: 'Senior',
        workType: 'Full time',
        location: 'Bangkok',
        salaryRange: '250,000 - 400,000',
        postedAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
      JobModel(
        id: '8',
        title: 'DevOps Engineer',
        companyName: 'CloudCorp',
        companyLogo: 'https://via.placeholder.com/60',
        matchPercentage: 83,
        level: 'Mid-level',
        workType: 'Full time',
        location: 'Bangkok',
        salaryRange: '180,000 - 300,000',
        postedAt: DateTime.now().subtract(const Duration(days: 2)),
      ),
      JobModel(
        id: '9',
        title: 'Marketing Specialist',
        companyName: 'MarketPro',
        companyLogo: 'https://via.placeholder.com/60',
        matchPercentage: 76,
        level: 'Junior',
        workType: 'Full time',
        location: 'Bangkok',
        salaryRange: '120,000 - 180,000',
        postedAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
      JobModel(
        id: '10',
        title: 'Business Analyst',
        companyName: 'BizTech',
        companyLogo: 'https://via.placeholder.com/60',
        matchPercentage: 81,
        level: 'Mid-level',
        workType: 'Full time',
        location: 'Bangkok',
        salaryRange: '160,000 - 250,000',
        postedAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
    ];
  }

  static List<CompanyModel> getTopCompanies() {
    return [
      const CompanyModel(
        id: '1',
        name: 'Gofive Company Limited',
        logo: 'https://via.placeholder.com/60',
        image: 'https://via.placeholder.com/300x150',
        description: 'บริษัท Gofive เรามี Passion ร่วมกันที่จะขับเคลื่อน Digital Transformation...',
        industry: 'Technology',
        employeeCount: 500,
        website: 'https://gofive.co.th',
      ),
      const CompanyModel(
        id: '2',
        name: 'บริษัท โซว์ไรจ์นิล จำกัด',
        logo: 'https://via.placeholder.com/60',
        image: 'https://via.placeholder.com/300x150',
        description: 'บริษัท โซว์ไรจ์นิล จำกัด ก่อตั้งขึ้นโดย "คุณหนุ่ย พงศ์สยุ หรือพูดกุณ์" (พริกสและผู้ผลิตรายการโครก์คนี) ประกอบ...',
        industry: 'Entertainment',
        employeeCount: 200,
        website: 'https://beartat.com',
      ),
      const CompanyModel(
        id: '3',
        name: 'TechCorp Solutions',
        logo: 'https://via.placeholder.com/60',
        image: 'https://via.placeholder.com/300x150',
        description: 'Leading technology solutions provider in Southeast Asia',
        industry: 'Technology',
        employeeCount: 1000,
        website: 'https://techcorp.com',
      ),
      const CompanyModel(
        id: '4',
        name: 'DataTech Analytics',
        logo: 'https://via.placeholder.com/60',
        image: 'https://via.placeholder.com/300x150',
        description: 'Advanced data analytics and AI solutions',
        industry: 'Data & Analytics',
        employeeCount: 300,
        website: 'https://datatech.com',
      ),
      const CompanyModel(
        id: '5',
        name: 'Innovation Inc',
        logo: 'https://via.placeholder.com/60',
        image: 'https://via.placeholder.com/300x150',
        description: 'Innovative product development company',
        industry: 'Product Development',
        employeeCount: 750,
        website: 'https://innovation-inc.com',
      ),
      const CompanyModel(
        id: '6',
        name: 'CloudCorp',
        logo: 'https://via.placeholder.com/60',
        image: 'https://via.placeholder.com/300x150',
        description: 'Cloud infrastructure and services provider',
        industry: 'Cloud Services',
        employeeCount: 400,
        website: 'https://cloudcorp.com',
      ),
      const CompanyModel(
        id: '7',
        name: 'MarketPro',
        logo: 'https://via.placeholder.com/60',
        image: 'https://via.placeholder.com/300x150',
        description: 'Digital marketing and advertising agency',
        industry: 'Marketing',
        employeeCount: 150,
        website: 'https://marketpro.com',
      ),
      const CompanyModel(
        id: '8',
        name: 'BizTech',
        logo: 'https://via.placeholder.com/60',
        image: 'https://via.placeholder.com/300x150',
        description: 'Business technology consulting firm',
        industry: 'Consulting',
        employeeCount: 600,
        website: 'https://biztech.com',
      ),
      const CompanyModel(
        id: '9',
        name: 'CreativeStudio',
        logo: 'https://via.placeholder.com/60',
        image: 'https://via.placeholder.com/300x150',
        description: 'Creative design and branding studio',
        industry: 'Design',
        employeeCount: 80,
        website: 'https://creativestudio.com',
      ),
      const CompanyModel(
        id: '10',
        name: 'FinTech Solutions',
        logo: 'https://via.placeholder.com/60',
        image: 'https://via.placeholder.com/300x150',
        description: 'Financial technology solutions provider',
        industry: 'FinTech',
        employeeCount: 450,
        website: 'https://fintech-solutions.com',
      ),
    ];
  }
}