//
//
// import '../src/features/job_board/models/company_model.dart';
// import '../src/features/job_board/models/job_model.dart';
//
// class MockData {
//   static List<JobModel> getRecommendedJobs() {
//     return [
//       JobModel(
//         id: '1',
//         title: 'UX/UI Designer',
//         companyName: 'Gofive',
//         companyLogo: 'assets/mock/company_logo_mock.png',
//         matchPercentage: 89,
//         level: 'Senior',
//         workType: 'Full time',
//         location: 'Bangkok',
//         salaryRange: '200,000 - 350,000',
//         postedAt: DateTime.now().subtract(const Duration(minutes: 1)),
//       ),
//       JobModel(
//         id: '2',
//         title: 'Sales Manager',
//         companyName: 'Gofive',
//         companyLogo: 'assets/mock/company_logo_mock.png',
//         matchPercentage: 79,
//         level: 'Senior',
//         workType: 'Full time',
//         location: 'Bangkok',
//         salaryRange: '200,000 - 350,000',
//         postedAt: DateTime.now().subtract(const Duration(minutes: 1)),
//       ),
//       JobModel(
//         id: '3',
//         title: 'Onboarding Specialist',
//         companyName: 'Gofive',
//         companyLogo: 'assets/mock/company_logo_mock.png',
//         matchPercentage: 78,
//         level: 'Senior',
//         workType: 'Full time',
//         location: 'Bangkok',
//         salaryRange: '200,000 - 350,000',
//         postedAt: DateTime.now().subtract(const Duration(minutes: 1)),
//       ),
//       JobModel(
//         id: '4',
//         title: 'Onboarding Specialist',
//         companyName: 'Gofive',
//         companyLogo: 'assets/mock/company_logo_mock.png',
//         matchPercentage: 78,
//         level: 'Senior',
//         workType: 'Full time',
//         location: 'Bangkok',
//         salaryRange: '200,000 - 350,000',
//         postedAt: DateTime.now().subtract(const Duration(hours: 2)),
//       ),
//       JobModel(
//         id: '5',
//         title: 'Frontend Developer',
//         companyName: 'TechCorp',
//         companyLogo: 'assets/mock/company_logo_mock.png',
//         matchPercentage: 85,
//         level: 'Mid-level',
//         workType: 'Full time',
//         location: 'Bangkok',
//         salaryRange: '150,000 - 250,000',
//         postedAt: DateTime.now().subtract(const Duration(hours: 3)),
//       ),
//       JobModel(
//         id: '6',
//         title: 'Data Scientist',
//         companyName: 'DataTech',
//         companyLogo: 'assets/mock/company_logo_mock.png',
//         matchPercentage: 92,
//         level: 'Senior',
//         workType: 'Full time',
//         location: 'Bangkok',
//         salaryRange: '300,000 - 450,000',
//         postedAt: DateTime.now().subtract(const Duration(hours: 5)),
//       ),
//       JobModel(
//         id: '7',
//         title: 'Product Manager',
//         companyName: 'Innovation Inc',
//         companyLogo: 'assets/mock/company_logo_mock.png',
//         matchPercentage: 87,
//         level: 'Senior',
//         workType: 'Full time',
//         location: 'Bangkok',
//         salaryRange: '250,000 - 400,000',
//         postedAt: DateTime.now().subtract(const Duration(days: 1)),
//       ),
//       JobModel(
//         id: '8',
//         title: 'DevOps Engineer',
//         companyName: 'CloudCorp',
//         companyLogo: 'assets/mock/company_logo_mock.png',
//         matchPercentage: 83,
//         level: 'Mid-level',
//         workType: 'Full time',
//         location: 'Bangkok',
//         salaryRange: '180,000 - 300,000',
//         postedAt: DateTime.now().subtract(const Duration(days: 2)),
//       ),
//       JobModel(
//         id: '9',
//         title: 'Marketing Specialist',
//         companyName: 'MarketPro',
//         companyLogo: 'assets/mock/company_logo_mock.png',
//         matchPercentage: 76,
//         level: 'Junior',
//         workType: 'Full time',
//         location: 'Bangkok',
//         salaryRange: '120,000 - 180,000',
//         postedAt: DateTime.now().subtract(const Duration(days: 3)),
//       ),
//       JobModel(
//         id: '10',
//         title: 'Business Analyst',
//         companyName: 'BizTech',
//         companyLogo: 'assets/mock/company_logo_mock.png',
//         matchPercentage: 81,
//         level: 'Mid-level',
//         workType: 'Full time',
//         location: 'Bangkok',
//         salaryRange: '160,000 - 250,000',
//         postedAt: DateTime.now().subtract(const Duration(days: 5)),
//       ),
//     ];
//   }
// //
// //   static List<CompanyModel> getTopCompanies() {
// //     return [
// //       const CompanyModel(
// //         id: '1',
// //         name: 'Gofive Company Limited',
// //         logo: 'assets/mock/company_logo_mock.png',
// //         image: 'assets/mock/company_image_mock.png',
// //         description: 'บริษัท Gofive เรามี Passion ร่วมกันที่จะขับเคลื่อน Digital Transformation...',
// //         industry: 'Technology',
// //         employeeCount: 500,
// //         website: 'https://gofive.co.th',
// //       ),
// //       const CompanyModel(
// //         id: '2',
// //         name: 'บริษัท โซว์ไรจ์นิล จำกัด',
// //         logo: 'assets/mock/company_logo_mock.png',
// //         image: 'assets/mock/company_image_mock.png',
// //         description: 'บริษัท โซว์ไรจ์นิล จำกัด ก่อตั้งขึ้นโดย "คุณหนุ่ย พงศ์สยุ หรือพูดกุณ์" (พริกสและผู้ผลิตรายการโครก์คนี) ประกอบ...',
// //         industry: 'Entertainment',
// //         employeeCount: 200,
// //         website: 'https://beartat.com',
// //       ),
// //       const CompanyModel(
// //         id: '3',
// //         name: 'TechCorp Solutions',
// //         logo: 'assets/mock/company_logo_mock.png',
// //         image: 'assets/mock/company_image_mock.png',
// //         description: 'Leading technology solutions provider in Southeast Asia',
// //         industry: 'Technology',
// //         employeeCount: 1000,
// //         website: 'https://techcorp.com',
// //       ),
// //       const CompanyModel(
// //         id: '4',
// //         name: 'DataTech Analytics',
// //         logo: 'assets/mock/company_logo_mock.png',
// //         image: 'assets/mock/company_image_mock.png',
// //         description: 'Advanced data analytics and AI solutions',
// //         industry: 'Data & Analytics',
// //         employeeCount: 300,
// //         website: 'https://datatech.com',
// //       ),
// //       const CompanyModel(
// //         id: '5',
// //         name: 'Innovation Inc',
// //         logo: 'assets/mock/company_logo_mock.png',
// //         image: 'assets/mock/company_image_mock.png',
// //         description: 'Innovative product development company',
// //         industry: 'Product Development',
// //         employeeCount: 750,
// //         website: 'https://innovation-inc.com',
// //       ),
// //       const CompanyModel(
// //         id: '6',
// //         name: 'CloudCorp',
// //         logo: 'assets/mock/company_logo_mock.png',
// //         image: 'assets/mock/company_image_mock.png',
// //         description: 'Cloud infrastructure and services provider',
// //         industry: 'Cloud Services',
// //         employeeCount: 400,
// //         website: 'https://cloudcorp.com',
// //       ),
// //       const CompanyModel(
// //         id: '7',
// //         name: 'MarketPro',
// //         logo: 'assets/mock/company_logo_mock.png',
// //         image: 'assets/mock/company_image_mock.png',
// //         description: 'Digital marketing and advertising agency',
// //         industry: 'Marketing',
// //         employeeCount: 150,
// //         website: 'https://marketpro.com',
// //       ),
// //       const CompanyModel(
// //         id: '8',
// //         name: 'BizTech',
// //         logo: 'assets/mock/company_logo_mock.png',
// //         image: 'assets/mock/company_image_mock.png',
// //         description: 'Business technology consulting firm',
// //         industry: 'Consulting',
// //         employeeCount: 600,
// //         website: 'https://biztech.com',
// //       ),
// //       const CompanyModel(
// //         id: '9',
// //         name: 'CreativeStudio',
// //         logo: 'assets/mock/company_logo_mock.png',
// //         image: 'assets/mock/company_image_mock.png',
// //         description: 'Creative design and branding studio',
// //         industry: 'Design',
// //         employeeCount: 80,
// //         website: 'https://creativestudio.com',
// //       ),
// //       const CompanyModel(
// //         id: '10',
// //         name: 'FinTech Solutions',
// //         logo: 'assets/mock/company_logo_mock.png',
// //         image: 'assets/mock/company_image_mock.png',
// //         description: 'Financial technology solutions provider',
// //         industry: 'FinTech',
// //         employeeCount: 450,
// //         website: 'https://fintech-solutions.com',
// //       ),
// //     ];
// //   }
// }